[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python run_ui.py --host=0.0.0.0 --port=$PORT"