[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python run_ui.py --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Core configuration
PORT = "8000"
PYTHONPATH = "."
RAILWAY_DEPLOYMENT = "true"

# Python environment
PYTHON_VERSION = "3.11"
PIP_VERSION = "23.3"

# Application settings
FLASK_ENV = "production"
FLASK_DEBUG = "false"

# OpenAI API (will be set via Railway dashboard)
# OPENAI_API_KEY = "sk-..."

# Enhanced trading system configuration
# LETTA_BASE_URL = "http://localhost:8283"
# REDIS_URL = "redis://localhost:6379" 
# SUPABASE_URL = "your_supabase_url"
# SUPABASE_ANON_KEY = "your_supabase_key"
# HYPERLIQUID_PRIVATE_KEY = "0x..."
# HYPERLIQUID_WALLET_ADDRESS = "0x..."
# HYPERLIQUID_TESTNET = "true"

[experimental]
configVersion = 1